# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: mufidtrade.github.io
title: Mufid Trade
email: faazabilamr084@gmail.com
author: Faaza Bil Amri
description: > # "Jual Beli Balance Dollar Paypal dan Pulsa Terpercaya. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016 Mufid Trade. All Rights Reserved.'
credits: 'Credits: Created by <a href="https://facebook.com/faazabilamri">Faaza Bil Amri</a><br/>Bootstrap theme by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/faazabilamri
  - title: facebook
    url: https://facebook.com/muhammadali2408
  - title: instagram
    url: https://instagram.com/mufidtrade
    
    # html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
  ignore:
  comments: ["<!--</body>-->"]
